### ISSUE TITLE
Error in injectionresponseparser.py

### ISSUE THREAD

**Issue by xbln** [socketlabs/socketlabs-python#5]
On unsuccessful injections (e.g. connection error or wrong API-key) a TypeError occurs in that module:

`Traceback (most recent call last):
  File "/usr/scripts/basic.py", line 31, in <module>
    response = client.send(message)
  File "/home/pi/.local/lib/python3.7/site-packages/socketlabs/injectionapi/socketlabsclient.py", line 104, in send
    return self.__send_basic_message(message)
  File "/home/pi/.local/lib/python3.7/site-packages/socketlabs/injectionapi/socketlabsclient.py", line 130, in __send_basic_message
    result = InjectionResponseParser.parse(data, response_code)
  File "/home/pi/.local/lib/python3.7/site-packages/socketlabs/injectionapi/core/injectionresponseparser.py", line 92, in parse
    injection_response = get_injection_response_dto(response)
  File "/home/pi/.local/lib/python3.7/site-packages/socketlabs/injectionapi/core/injectionresponseparser.py", line 63, in get_injection_response_dto
    for item in dct['MessageResults']:
TypeError: 'NoneType' object is not iterable`

You can test it with your basic send example.

**Comment by modaopokimi** [comment]
@xbln Replace 10000 with your server id
client = SocketLabsClient(10000, "YOUR-API-KEY");

**Comment by xbln** [comment]
I don´t get your point. I reported a type error on unsuccessful injections. Did you fix that?

**Comment by modaopokimi** [comment]
Make sure you add your server-id

client = SocketLabsClient("SERVER_ID", "YOUR-API-KEY");
